import { useEffect, useState } from 'react';
import { api, apiErrorMessage } from '../../api/client.js';
import { Modal } from '../../components/ui/Modal.jsx';
import { TextInput, SelectInput, TextArea } from '../../components/ui/Field.jsx';
import { useToast } from '../../components/ui/Toast.jsx';
import { useI18n } from '../../i18n/I18nContext.jsx';
import { CARGO_STATUSES } from '../../lib/constants.js';
import { baht } from '../../lib/format.js';

const toLocalInput = (d) => (d ? new Date(d).toISOString().slice(0, 16) : '');

export function CargoForm({ open, onClose, batch, onSaved }) {
  const toast = useToast();
  const { t } = useI18n();
  const editing = !!batch;
  const [saving, setSaving] = useState(false);
  const [form, setForm] = useState(null);

  useEffect(() => {
    if (!open) return;
    setForm({
      origin: batch?.origin || 'Bangkok',
      destination: batch?.destination || 'Mandalay',
      weight: batch?.weight ?? '',
      cargoRate: batch?.cargoRate ?? '',
      status: batch?.status || 'pending',
      note: batch?.note || '',
      departureDate: toLocalInput(batch?.departureDate),
      arrivalDate: toLocalInput(batch?.arrivalDate),
    });
  }, [open, batch]);

  if (!open || !form) return null;

  const estTotal =
    form.weight !== '' && form.cargoRate !== '' ? Number(form.weight) * Number(form.cargoRate) : null;

  const submit = async (e) => {
    e.preventDefault();
    // Batch code is always auto-generated by the server — never sent from the form.
    const payload = {
      origin: form.origin || 'Bangkok',
      destination: form.destination || 'Mandalay',
      weight: form.weight === '' ? undefined : Number(form.weight),
      cargoRate: form.cargoRate === '' ? undefined : Number(form.cargoRate),
      status: form.status,
      note: form.note || null,
      departureDate: form.departureDate ? new Date(form.departureDate).toISOString() : null,
      arrivalDate: form.arrivalDate ? new Date(form.arrivalDate).toISOString() : null,
    };
    setSaving(true);
    try {
      if (editing) await api.put(`/cargo/${batch.cargoId}`, payload);
      else await api.post('/cargo', payload);
      toast.success(editing ? t('toast.cargoUpdated') : t('toast.cargoCreated'));
      onSaved?.();
      onClose();
    } catch (err) {
      toast.error(apiErrorMessage(err));
    } finally {
      setSaving(false);
    }
  };

  return (
    <Modal
      open={open}
      onClose={onClose}
      size="lg"
      title={editing ? t('cargoForm.edit', { code: batch.cargoBatchCode }) : t('cargoForm.new')}
      footer={
        <>
          <button className="btn-secondary" onClick={onClose}>
            {t('common.cancel')}
          </button>
          <button className="btn-primary" onClick={submit} disabled={saving}>
            {saving ? t('common.saving') : t('common.save')}
          </button>
        </>
      }
    >
      <form onSubmit={submit} className="grid gap-3 sm:grid-cols-2">
        {!editing && (
          <p className="rounded-lg bg-panel2 px-3 py-2 text-xs text-ink2 sm:col-span-2">
            {t('cargoForm.codeAuto')}
          </p>
        )}
        <SelectInput
          label={t('col.status')}
          includeBlank={false}
          value={form.status}
          onChange={(e) => setForm({ ...form, status: e.target.value })}
          options={CARGO_STATUSES.map((s) => ({ value: s, label: t(`status.cargo.${s}`) }))}
        />
        <div className="hidden sm:block" />
        <TextInput
          label={t('cargoForm.origin')}
          value={form.origin}
          onChange={(e) => setForm({ ...form, origin: e.target.value })}
        />
        <TextInput
          label={t('cargoForm.destination')}
          value={form.destination}
          onChange={(e) => setForm({ ...form, destination: e.target.value })}
        />
        <TextInput
          label={t('cargoForm.weight')}
          type="number"
          step="0.01"
          value={form.weight}
          onChange={(e) => setForm({ ...form, weight: e.target.value })}
        />
        <TextInput
          label={t('cargoForm.rate')}
          type="number"
          step="0.01"
          value={form.cargoRate}
          onChange={(e) => setForm({ ...form, cargoRate: e.target.value })}
        />
        <div className="flex items-end text-sm text-ink2 sm:col-span-2">
          {estTotal != null && <span>{t('cargoForm.totalCost', { v: baht(estTotal) })}</span>}
        </div>
        <TextInput
          label={t('cargoForm.departure')}
          type="datetime-local"
          value={form.departureDate}
          onChange={(e) => setForm({ ...form, departureDate: e.target.value })}
        />
        <TextInput
          label={t('cargoForm.arrival')}
          type="datetime-local"
          value={form.arrivalDate}
          onChange={(e) => setForm({ ...form, arrivalDate: e.target.value })}
        />
        <TextArea
          label={t('cargoForm.note')}
          className="sm:col-span-2"
          value={form.note}
          onChange={(e) => setForm({ ...form, note: e.target.value })}
        />
      </form>
    </Modal>
  );
}
